### ISSUE TITLE
[Bug] cannot login

### ISSUE THREAD

**Issue by KiriKira** [redphx/better-xcloud-android#10]
**Platform**
- Device name: samsung zfold 5
- Device type (phone/TV): phone
- Android version: 14
- App version: 0.1
- Script version: ...

**Describe the bug**
Cannot login after input the code in browser

**Screenshots/Videos**
![Screenshot_20240317_120954_Firefox Nightly](https://github.com/redphx/better-xcloud-android/assets/32393884/9953c3e2-a84e-4a7b-ab3f-2775aab72dc6)

![Screenshot_20240317_121009_BetterXC](https://github.com/redphx/better-xcloud-android/assets/32393884/3ffb8d83-a35b-487f-b9cd-02ca1ad7e0fd)

**Comment by darkSTONP** [comment]
In this Microsoft guide you just have to enter the code

**Comment by KiriKira** [comment]
Yes, I have entered the code, and the first screenshot shows I have successfully logined, but when I return to the app nothing happens. Is there any log I can export?

**Comment by KiriKira** [comment]
Well, I tried leaving the App in the foreground and using a PC browser to access xbox.com/tvsetup, and this time I could log in successfully. 
So this looks like it's missing the login session because the app's background activity is limited?

**Comment by KingNothing81** [comment]
@redphx: Are you somehow forcing the "TV Login" screen? Because when using Kiwi, you can just login directly with entering username and password. Doing the login with the help of another device can be more comfortable of course. But if you don't have another device nearby, I think it would be good if you could also bypass that method and log in directly.

And by the way ... like on the screenshot posted by @KiriKira , the screen also failed to load/show the QR code in my case.

**Comment by redphx** [comment]
Fixed in 0.2
