### ISSUE TITLE
[Feature] Android TV banner icon and adapative icon for smartphone/tablets

### ISSUE THREAD

**Issue by piersandro** [redphx/better-xcloud-android#126]
### Device

TV

### Device name

Amazon Fire TV Stick 4K Max

### Android Version

FireOS 8/Android 11

### Suggestion

Follow these guidelines to add the Android TV Icon Banner:
https://developer.android.com/design/ui/tv/guides/system/tv-app-icon-guidelines

[![image](https://github.com/user-attachments/assets/a573eda1-8ed9-4932-9250-666052a5e01f)](https://developer.android.com/static/design/ui/tv/guides/system/images/icons/banner-sizes.webp)

and these guidelines to create adaptive icon for smartphone/tablet:
https://developer.android.com/develop/ui/views/launch/icon_design_adaptive

[![image](https://github.com/user-attachments/assets/87705788-93fc-4292-bb27-08b307b40c02)](https://developer.android.com/static/guide/practices/ui_guidelines/images/article_icon_adaptive.gif)

It would be good to understand how to create Logitech G Cloud banners but I have not found any information regarding this.

**Comment by redphx** [comment]
The app already implemented Adaptive icon and TV banner.  
I gifted my G Cloud to my brother so I don't have it any more. And I don't use its default launcher.

**Comment by piersandro** [comment]
I suggested the Android TV banner because on Fire TV it doesn't appear as banner. It shows the icon. 

![image](https://github.com/user-attachments/assets/21a8a95b-7214-4214-b6ea-70e6fa85cf5a)

Probably it uses a different format. 

On Logitech G Cloud I use Console Launcher, but on official launcher only a few apps have the banner instead of the icon.

**Comment by redphx** [comment]
This is a problem of Fire TV Stick: https://old.reddit.com/r/firetvstick/comments/16ue8f2/new_2023_4k_max_stick_does_not_show_icons_for/

**Comment by KingNothing81** [comment]
@piersandro: FireOS pulls the banner icon of apps from Amazon's servers, not from the app package. And sideloaded apps always show up like this: With the small icon inside a grey square. But even that was broken for a while, as @redphx showed with the provided link. So the only way to fix that would be to put the app on Amazon's app store.

But talking about that: I noticed that the corners of the Android TV banner look strange. They are not green. 
@redphx: Did you round the corners already when doing the icon? Because I think that's something the launcher does. So the banner should have a square format without rounded corners. I can provide a picture later to show what I mean.

**Comment by KingNothing81** [comment]
Here is a picture of the Android TV banner icon:

![IMG_0271](https://github.com/user-attachments/assets/87e87230-c640-4727-9404-5151dee8e251)

If you zoom in a little bit more you can see something is “wrong” with the corners: They aren’t green, but dark grey. That’s not the case with the GFN banner. I think that’s because the source icon already has rounded, transparent corners.

Sorry, for the nitpicking. If another user hadn’t brought up that topic app, I wouldn’t have mentioned it.

**Comment by redphx** [comment]
It should be a gree rectangle. Must be launcher's bug.  
I'm gonna close this issue since it's launcher's issue.
