### ISSUE TITLE
[Bug] `☰` button of the Xbox controller doesn't work

### ISSUE THREAD

**Issue by PhunkyBob** [redphx/better-xcloud-android#133]
### Device

TV

### Device name

Amazon FireTV 4K

### Android Version

13

### App version

0.19.0

### Script version

?

### WebView name and version

?

### Reproduction Steps

- I connect my Xbox One controller to my FireTV stick.
- I launch Better-Xcloud.
- I launch the game "Magical Delicacy".
- In the game, I press `☰` button of the Xbox controller.

## Expected result

- The menu with the "save" option pops.

## Actual result

- I hear a "plop" sound, but the menu doesn't appear.

## Additional informations

- Under Windows, it works.
- With the official Microsoft Xbox application on FireTV, it doesn't work either.

**Comment by redphx** [comment]
This is a common problem with the Fire TV Stick:  

- https://old.reddit.com/r/xcloud/comments/11gcpi8/xbox_game_pass_on_fire_stick_with_controller/
- https://old.reddit.com/r/xcloud/comments/pe4hgp/menu_button_stopped_working_on_amazon_fire/

**Comment by KingNothing81** [comment]
@PhunkyBob: You should check if your controller has a firmware update available and install it. With most current firmware, it should at least work with the official app now.

**Comment by PhunkyBob** [comment]
I've done the firmware upgrade of the controller and updated the native Xbox application: same thing. The `☰` button does nothing but a "click" in the game, instead of opening the main menu.

**Comment by KingNothing81** [comment]
Hm ... sorry to hear that. I followed a discussion on Reddit where a user had a similiar problem with wrong button mapping using the Xbox app on Fire TV. And the firmware update solved the problem.

That's what the official press release says about compatible controllers:

> Then, all you have to do is connect a compatible Bluetooth controller and you’re ready to start gaming! The Xbox Wireless Controller, Xbox Adaptive Controller, DualSense or DualShock 4 controllers all work seamlessly. Once connected, you're all set!

https://www.aboutamazon.com/news/devices/xbox-gaming-on-amazon-fire-tv

So maybe the problem is that Xbox One controllers are too old and not supported? 

You could get a cheap third party DS4 controller and give that one a try. Ironically those should work for playing Xbox games on your Amazon Fire TV device. ;)

**Comment by PhunkyBob** [comment]
> So maybe the problem is that Xbox One controllers are too old and not supported?

LOL, I've bought this controller few weeks ago for this purpose only ^^

**Comment by KingNothing81** [comment]
I can also still buy PS3 controllers. But those won't also be supported from the Xbox app on Fire TV, just PS4 (DualShock) and PS5 (DualSense) controllers.

**Comment by PhunkyBob** [comment]
It seems fixed with the last Firestick update 🚀
