### ISSUE TITLE
[Bug] select button xbox controller shield tv

### ISSUE THREAD

**Issue by H34M35** [redphx/better-xcloud-android#81]
### Device

Other

### Device name

nvidia shield tv pro 2019

### Android Version

11

### App version

0.11. 0

### Script version

3.5.3

### Reproduction Steps

hello, I use the app better xcloud on my shield tv pro. it is very good but the select button of my Xbox controller doesn't work, it's not recognized by the app. Thank you for your work and for helping me.

**Comment by KingNothing81** [comment]
This is a Shield TV specific problem caused by a system modification by NVIDIA that remaps some controller buttons on a system level.

You can solve this by disabling the following system package …

 NVIDIA ShieldTech
**com.nvidia.shieldtech.hooks**

A comfortable way to do this wold be to use the ADB TV app:
https://play.google.com/store/apps/details?id=com.cybercat.adbappcontrol.tv

After disabling the package and restarting your Shield, all controller buttons should work as expected. Including the middle Nexus button, that can now be used to open the Xbox guide menu.

**Comment by H34M35** [comment]
thank you for you tops, my controller works perfectly now :-) Le 21 avr. 2024 23:47, KingNothing81 ***@***.***> a écrit :
This is a Shield TV specific problem caused by a system modification by NVIDIA that remaps some controller buttons on a system level.
You can solve this by disabling the following system package …
NVIDIA ShieldTech
com.nvidia.shieldtech.hooks
A comfortable way to do this wold be to use the ADB TV app:
https://play.google.com/store/apps/details?id=com.cybercat.adbappcontrol.tv
After disabling the package and restarting your Shield, all controller buttons should work as expected. Including the middle Nexus button, that can now be used to open the Xbox guide menu.
